---
summary: Complete GitHub Actions workflow for automated weekly updates
last_updated: 2025-06-26
last_updated_by: dex
last_update: Created comprehensive weekly update automation workflow
---

# Weekly Update Automation Workflow

name: Weekly Update Automation
on:
  schedule:
    # Every Friday at 3pm PST (11pm UTC)
    - cron: '0 23 * * 5'
  workflow_dispatch:
    inputs:
      draft_mode:
        description: 'Create draft PR instead of direct commit'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  weekly-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git analysis
      
      - name: Set up Claude Code
        run: |
          # Install Claude Code if not available
          which claude || curl -fsSL https://claude.ai/install.sh | sh
      
      - name: Run Weekly Update SOP
        run: |
          claude -p "Execute the complete weekly update SOP following these steps:
          
          1. First, determine the current date and upcoming Friday date
          2. Check if a weekly update already exists for this Friday
          3. Update financial metrics:
             - Run stripe-metrics-collector to get MRR and customer count
             - Run mercury-bank-fetcher to get cash balance and burn rates
             - Update metrics/README.md with all current metrics
          4. Gather development updates:
             - Run linear-integration to get completed tickets from last 7 days
             - Use git-history-summarizer to analyze commits in both repos
             - Summarize key technical accomplishments
          5. Collect thought leadership:
             - Run social-media-fetcher for Dexter's posts from last week
             - Select high-engagement content for 'What We're Thinking About'
          6. Create the weekly update entry in weekly-updates.md:
             - Follow the existing format with narrative summary
             - Include all metrics with week-over-week changes
             - Add key accomplishments and customer highlights
             - Include next week focus items
          7. Update journal.md with what was done
          
          Ensure all updates follow the existing format and maintain consistency."
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          MERCURY_API_KEY: ${{ secrets.MERCURY_API_KEY }}
          MERCURY_API_SECRET: ${{ secrets.MERCURY_API_SECRET }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
      
      - name: Create Pull Request or Commit
        if: success()
        run: |
          if [[ "${{ github.event.inputs.draft_mode }}" == "true" ]]; then
            # Create a new branch and PR
            BRANCH_NAME="weekly-update-$(date +%Y-%m-%d)"
            git checkout -b $BRANCH_NAME
            git add .
            git commit -m "Weekly update for $(date +%Y-%m-%d)
            
            - Updated financial metrics from Stripe and Mercury
            - Added completed work from Linear
            - Included thought leadership content
            - Updated journal with changes"
            
            git push origin $BRANCH_NAME
            
            gh pr create \
              --title "Weekly Update - $(date +%Y-%m-%d)" \
              --body "Automated weekly update generated by GitHub Actions.
              
              ## Changes
              - Updated metrics/README.md with current financials
              - Added weekly update entry to weekly-updates.md
              - Updated journal.md
              
              Please review before merging." \
              --draft
          else
            # Direct commit to main
            git add .
            git commit -m "Weekly update for $(date +%Y-%m-%d)" || echo "No changes to commit"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## Required Secrets Configuration

The following secrets must be configured in the repository:

1. **ANTHROPIC_API_KEY** - For Claude Code
2. **STRIPE_API_KEY** - For revenue metrics
3. **MERCURY_API_KEY** - For bank balance
4. **MERCURY_API_SECRET** - For Mercury auth
5. **LINEAR_API_KEY** - For ticket data
6. **TWITTER_API_KEY** - For Twitter posts
7. **TWITTER_API_SECRET** - For Twitter auth
8. **TWITTER_ACCESS_TOKEN** - For Twitter API
9. **TWITTER_ACCESS_SECRET** - For Twitter API
10. **LINKEDIN_CLIENT_ID** - For LinkedIn posts
11. **LINKEDIN_CLIENT_SECRET** - For LinkedIn auth
12. **LINKEDIN_ACCESS_TOKEN** - For LinkedIn API

## Files Modified

This workflow will modify the following files:
- `metrics/README.md` - Updated financial metrics
- `weekly-updates.md` - New weekly update entry
- `journal.md` - Record of changes made

## Manual Trigger

The workflow can be manually triggered with the option to create a draft PR instead of directly committing to main. This is useful for review before publishing.