/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/extract-vscode-themes.ts
 * Generated at: 2025-10-10T15:58:03.267Z
 * Source: theme-registry.json + theme-token-mapping.json
 *
 * To regenerate: bun run extract-vscode-themes
 */

import type { Theme } from '@/contexts/ThemeContext'
import { Moon } from 'lucide-react'

export interface VSCodeThemeMetadata {
  value: Theme
  label: string
  icon: React.ComponentType<{ className?: string }>
  type: 'dark' | 'light'
}

export const vscodeThemes: VSCodeThemeMetadata[] = [
  {
    value: 'tokyo-night-light-vscode' as Theme,
    label: 'Tokyo Night Light',
    icon: Moon,
    type: 'dark',
  },
]
