/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/extract-vscode-themes.ts
 * Generated at: 2025-10-10T23:32:40.138Z
 * Source: theme-registry.json + theme-token-mapping.json
 *
 * To regenerate: bun run extract-vscode-themes
 */

import type { Theme } from '@/contexts/ThemeContext'
import { Moon, Sun } from 'lucide-react'

export interface VSCodeThemeMetadata {
  value: Theme
  label: string
  icon: React.ComponentType<{ className?: string }>
  type: 'dark' | 'light'
}

export const vscodeThemes: VSCodeThemeMetadata[] = [
  {
    value: 'tokyo-night-vscode' as Theme,
    label: 'Tokyo Night',
    icon: Moon,
    type: 'dark',
  },
  {
    value: 'tokyo-night-light-vscode' as Theme,
    label: 'Tokyo Night Light',
    icon: Moon,
    type: 'dark',
  },
  {
    value: 'tokyo-night-storm-vscode' as Theme,
    label: 'Tokyo Night Storm',
    icon: Moon,
    type: 'dark',
  },
  {
    value: 'rosé-pine-vscode' as Theme,
    label: 'Rosé Pine',
    icon: Moon,
    type: 'dark',
  },
  {
    value: 'rosé-pine-dawn-vscode' as Theme,
    label: 'Rosé Pine Dawn',
    icon: Sun,
    type: 'light',
  },
  {
    value: 'rosé-pine-moon-vscode' as Theme,
    label: 'Rosé Pine Moon',
    icon: Moon,
    type: 'dark',
  },
]
