#!/usr/bin/env bun

/**
 * VS Code Theme Extraction Tool
 *
 * Reads theme-registry.json, clones repositories, extracts theme JSON files,
 * applies user-defined mappings from theme-token-mapping.json, and generates:
 * - src/styles/vscode-themes.generated.css
 * - src/components/vscode-themes.generated.ts
 */

import { readFile, writeFile } from 'fs/promises'
import { resolve } from 'path'
import { exec } from 'child_process'
import { promisify } from 'util'
import { existsSync } from 'fs'
import { parse } from 'jsonc-parser'

const execAsync = promisify(exec)

interface ThemeRegistry {
  themes: Array<{
    repo: string
    themes: string[]  // Array of theme file paths
  }>
}

interface TokenMapping {
  colorMappings: Record<string, string>  // vscodeToken → cssVariable
  tokenColorMappings: Record<string, string>  // Future use
  fallbacks: {
    dark: { icon: string }
    light: { icon: string }
  }
}

interface VSCodeThemeJSON {
  name: string
  type: 'dark' | 'light'
  colors: Record<string, string>
  tokenColors?: Array<{
    scope: string | string[]
    settings: {
      foreground?: string
      background?: string
      fontStyle?: string
    }
  }>
}

interface ExtractedTheme {
  id: string  // e.g., "tokyo-night-vscode"
  name: string  // e.g., "Tokyo Night"
  type: 'dark' | 'light'
  cssVariables: Map<string, string>  // CSS var name → hex color
}

async function ensureRepository(repoUrl: string): Promise<string> {
  // Extract repo name from URL (e.g., "tokyo-night-vscode-theme")
  const repoName = repoUrl.split('/').pop()?.replace('.git', '') || 'unknown'
  const clonePath = resolve(__dirname, '..', 'themeClones', repoName)

  if (existsSync(clonePath)) {
    console.log(`📦 Updating ${repoName}...`)
    await execAsync('git pull', { cwd: clonePath })
  } else {
    console.log(`📥 Cloning ${repoUrl}...`)
    const themeClonesDir = resolve(__dirname, '..', 'themeClones')
    await execAsync(`mkdir -p ${themeClonesDir}`)
    await execAsync(`git clone ${repoUrl} ${clonePath}`)
  }

  return clonePath
}

async function readThemeFile(clonePath: string, themeFile: string): Promise<VSCodeThemeJSON> {
  const fullPath = resolve(clonePath, themeFile)
  const content = await readFile(fullPath, 'utf-8')
  // Use Microsoft's JSONC parser to handle comments and trailing commas
  return parse(content) as VSCodeThemeJSON
}

function applyMappings(
  themeJson: VSCodeThemeJSON,
  mappings: TokenMapping
): ExtractedTheme {
  const cssVariables = new Map<string, string>()

  // Apply color mappings
  for (const [vscodeToken, cssVariable] of Object.entries(mappings.colorMappings)) {
    const vscodeColor = themeJson.colors[vscodeToken]
    if (vscodeColor) {
      cssVariables.set(cssVariable, vscodeColor)
    }
  }

  // Generate theme ID (kebab-case name + "-vscode")
  const id = themeJson.name.toLowerCase().replace(/\s+/g, '-') + '-vscode'

  return {
    id,
    name: themeJson.name,
    type: themeJson.type,
    cssVariables,
  }
}

async function main() {
  console.log('🎨 VS Code Theme Extraction Tool')
  console.log('================================\n')

  // Load configuration
  const registryPath = resolve(__dirname, '..', 'theme-registry.json')
  const mappingPath = resolve(__dirname, '..', 'theme-token-mapping.json')

  const registry: ThemeRegistry = JSON.parse(await readFile(registryPath, 'utf-8'))
  const mappings: TokenMapping = JSON.parse(await readFile(mappingPath, 'utf-8'))

  console.log(`📋 Found ${registry.themes.length} theme repositories\n`)

  const extractedThemes: ExtractedTheme[] = []

  // Process each repository
  for (const repoConfig of registry.themes) {
    console.log(`\n📚 Processing: ${repoConfig.repo}`)

    // Ensure repository is cloned/updated
    const clonePath = await ensureRepository(repoConfig.repo)

    // Process each theme file in the repository
    for (const themeFile of repoConfig.themes) {
      console.log(`  📄 Extracting ${themeFile}...`)

      const themeJson = await readThemeFile(clonePath, themeFile)
      const extracted = applyMappings(themeJson, mappings)

      extractedThemes.push(extracted)

      console.log(`     ✅ Extracted "${extracted.name}" (${extracted.cssVariables.size} variables)`)
    }
  }

  console.log(`\n📊 Total themes extracted: ${extractedThemes.length}`)

  if (extractedThemes.length === 0) {
    console.log('\n⚠️  No themes extracted (check mappings and enabled flags)')
    return
  }

  console.log('\n📝 Generating output files...')

  await writeCSSFile(extractedThemes)
  await writeTypeScriptFile(extractedThemes, mappings)

  console.log('\n✅ Done')
}

function generateCSS(themes: ExtractedTheme[]): string {
  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/extract-vscode-themes.ts
 * Generated at: ${new Date().toISOString()}
 * Source: theme-registry.json + theme-token-mapping.json
 *
 * To regenerate: bun run extract-vscode-themes
 */

`

  const themeSections = themes.map(theme => {
    const variables = Array.from(theme.cssVariables.entries())
      .map(([varName, color]) => `  ${varName}: ${color};`)
      .join('\n')

    return `/* ${theme.name} (${theme.type}) */
[data-theme='${theme.id}'] {
${variables}
}`
  }).join('\n\n')

  return header + themeSections + '\n'
}

async function writeCSSFile(themes: ExtractedTheme[]) {
  const cssPath = resolve(__dirname, '..', 'src', 'styles', 'vscode-themes.generated.css')
  const cssContent = generateCSS(themes)

  await writeFile(cssPath, cssContent, 'utf-8')
  console.log(`  📝 Wrote ${cssPath}`)
}

function generateTypeScript(themes: ExtractedTheme[], mappings: TokenMapping): string {
  // Determine which icons we actually need
  const needsMoon = themes.some(t => t.type === 'dark')
  const needsSun = themes.some(t => t.type === 'light')

  const imports = []
  if (needsMoon) imports.push('Moon')
  if (needsSun) imports.push('Sun')

  const iconImport = imports.length > 0 ? `import { ${imports.join(', ')} } from 'lucide-react'\n` : ''

  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/extract-vscode-themes.ts
 * Generated at: ${new Date().toISOString()}
 * Source: theme-registry.json + theme-token-mapping.json
 *
 * To regenerate: bun run extract-vscode-themes
 */

import type { Theme } from '@/contexts/ThemeContext'
${iconImport}
export interface VSCodeThemeMetadata {
  value: Theme
  label: string
  icon: React.ComponentType<{ className?: string }>
  type: 'dark' | 'light'
}

`

  const themeArray = themes.map(theme => {
    const icon = theme.type === 'dark'
      ? mappings.fallbacks.dark.icon
      : mappings.fallbacks.light.icon

    const iconComponent = icon === 'moon' ? 'Moon' : 'Sun'

    return `  {
    value: '${theme.id}' as Theme,
    label: '${theme.name}',
    icon: ${iconComponent},
    type: '${theme.type}',
  }`
  }).join(',\n')

  return header + `export const vscodeThemes: VSCodeThemeMetadata[] = [\n${themeArray},\n]\n`
}

async function writeTypeScriptFile(themes: ExtractedTheme[], mappings: TokenMapping) {
  const tsPath = resolve(__dirname, '..', 'src', 'components', 'vscode-themes.generated.ts')
  const tsContent = generateTypeScript(themes, mappings)

  await writeFile(tsPath, tsContent, 'utf-8')
  console.log(`  📝 Wrote ${tsPath}`)
}

main().catch((err) => {
  console.error('❌ Error:', err)
  process.exit(1)
})
